### ISSUE TITLE
Invisible wall in Catwalk area

### ISSUE THREAD

**Issue by schkuromi** [JoshMate/Monolith#1]
There appears to be some kind of invisible wall in the Catwalk hold area that blocks the player from walking through it

I've highlighted roughly where it is here:
![image](https://user-images.githubusercontent.com/32804728/85939765-ad092e80-b94a-11ea-8d96-92499b894b52.png)

**Comment by JoshMate** [comment]
Very strange, I've just loaded up Unity and all invisible walls in this hold are where they should be, I will investigate in-game to see if it appears there midway through the game.

**Comment by schkuromi** [comment]
Here's a video showcasing it, if it would help you.
This also happens regardless of whether it is an active Hold area.

[![](http://img.youtube.com/vi/mJKcPGaVBNY/0.jpg)](http://www.youtube.com/watch?v=mJKcPGaVBNY "")

**Comment by JoshMate** [comment]
Ah yes I managed to get it in-game, it's a strange one, but it will be fixed in the next update, Thanks for the heads up!

**Comment by JoshMate** [comment]
Done and new version released.
