### ISSUE TITLE
New Treehouse Hold Not Accesible

### ISSUE THREAD

**Issue by Sirpotatos** [JoshMate/Monolith#3]
Not sure if you're aware, but the "ropes" in the new treehouse hold are not climable. The platforms are also too high to teleport on to, so it's impossible to get up to the hold point right now. Just wanted to let you know since it becomes unplayable if you get this hold point. Thanks for all your hard work on this map! The lighting looks fantastic now.

**Comment by JoshMate** [comment]
Hi, Sirpotatos 

This is very strange, I have tested the hold multiple times and can't see anything wrong in Unity. Could you please provide a video of the ropes "Not working" please so I can better see what is going on with your game.

**Comment by JoshMate** [comment]
Hi,

I just tested it again in live to double-check, and the ropes at treehouse all work. Even on different locomotion settings. 

Could you please tell me the following:

1. What Headset and controllers you use

2. What Locomotion mode you use

3. What version of WurstMOD you are on "H3VR/WurstMod Changelog.txt"

And installing the latest version of wurstmod may fix your issues.

**Comment by Sirpotatos** [comment]
Here is a video of the issue as previously requested:  https://www.youtube.com/watch?v=502aLE1GbDs&feature=youtu.be

As you can see I tried swapping around different interaction settings and turned off the WIP settings to no avail.

1. I am using og HTC Vive HMD with Valve index controllers.
2. I use armswinger, but confirmed that it does not work for any locomotion mode.
3. I am on Wurstmod V 1.2.0.0

I will try updating to Wurstmod 1.3.0.0 and see if that is the issue.

UPDATE:  Updating to Wurstmod 1.3.0.0 fixed the issue! Thanks for helping me troubleshoot this. I hadn't realized Wurstmod had been updated.
